### ISSUE TITLE
OAuth: Client ID not sent

### ISSUE THREAD

**Issue by Schwefelhexa** [frencojobs/vscode-vercel#2]
When clicking "Log in with Vercel", `https://vercel.com/oauth/authorize?state=4SpZuzaLSpnd1-C3-ELok&version=` gets opened and shows a 404.
My guess is you aren't sending the OAuth client ID.

**Comment by frencojobs** [comment]
Omg yes, VSCode is not picking the dotenv variables when run in the release mode I guess. Trying to fix it as fast as I could.

**Comment by frencojobs** [comment]
Fixed by downgrading the webpack and webpack-cli, and adding the dotenv-webpack@4.0.0 to load environment variables into the build files. Have tested and should be working now. Thanks for quickly reporting the issue.

P.S. Downgrading webpack is necessary due to [this issue](https://github.com/mrsteele/dotenv-webpack/issues/271).
